version: '3.5'

services:

  client:
    container_name: kaleido-table-client
    build:
      context: ./client
      dockerfile: 'Dockerfile'
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  controller:
    container_name: kaleido-table-controller
    build:
      context: ./controller
      dockerfile: 'Dockerfile'
    volumes:
      - './controller:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4000:3000'
    environment:
      - NODE_ENV=development

  server:
    container_name: kaleido-table-server
    build:
      context: ./server
      dockerfile: 'Dockerfile'
    user: "node"
    environment:
      - NODE_ENV=production
    ports:
      - '5000:5000'
    volumes:
      - ./server:/usr/src/app
      - '/usr/src/app/node_modules'
    links:
      - mongodb-primary

  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
    volumes:
      - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017

volumes:
  mongodb_master_data:
    driver: local

